### ISSUE TITLE
"Tradable Subscriptions" Messing Up Spacing

### ISSUE THREAD

**Issue by alecchendev** [IlliniBlockchain/buoyant#30]
Didn't realize this till it was already up - 2 lines for "tradable subscriptions" makes the cards uneven - fix by making font smaller or smth..? Maybe even change back to "liquid subscriptions"

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/30279834/158513536-9da1de7e-0bd0-444b-9ffb-80775520884a.png">

**Comment by jdubpark** [comment]
We could use `white-space: nowrap` to force the text to be in one line, but that might overflow the box horizontally. So either:
(1) Smaller font, but this might make other titles kinda too small
(2) Make other titles two-liners too

I'd say (2) is better but lmk what you think.

**Comment by alecchendev** [comment]
I think try to smush onto one line, even if it goes past the padding a lil if it looks fine then its all good (can do this + make font only slightly smaller if that's how the cookie crumbles lol)

could also try to adjust spacing between descriptions and titles to make them a lil more even - i think this might be better instead of making other two 2 liners (unless this is what you meant) just because im thinking something like  "wicked" then "fast" underneath would look weird

just play around, if u find something that just looks okay/a bit better than how it is currently, should be fiiiine
